### ISSUE TITLE
Packer build issue

### ISSUE THREAD

**Issue by tsusadivyago** [wso2/terraform-is#7]
packer build centos-base.json
azure-arm output will be in this color.

1 error(s) occurred:

* Bad source './ansible-ei': stat ./ansible-ei: no such file or directory

----------------
update the folder to be used : https://github.com/wso2/terraform-is/blob/master/azure-simple/packer/centos-base.json

{
      "type": "file",
      "source": "./ansible-is",
      "destination": "/tmp"
    },

**Comment by tsusadivyago** [comment]
Encountered another error:

packer build centos-base.json
azure-arm output will be in this color.

==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using client secret
    azure-arm: Creating Azure Resource Manager (ARM) client ...
Build 'azure-arm' errored: Cannot locate the managed image resource group WSO2-installers.

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Cannot locate the managed image resource group WSO2-installers.

==> Builds finished but no artifacts were created.

**Comment by madurangasiriwardena** [comment]
Closing the issue due to the inactivity of the repository
